name: wasdrop
description: Fruity Drop - merge drop game (internal name wasdrop)
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.5.0"
  flutter: ">=3.27.0"

dependencies:
  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  navigation:
    path: ./navigation
  features:
    path: ./features

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flame: ^1.38.0

flutter:
  uses-material-design: true

  assets:
    - core/resources/audio/
    - core/resources/fonts/OFL-Rubik.txt
    - core/resources/fonts/OFL-Unbounded.txt
  fonts:
    - family: Rubik
      fonts:
        - asset: core/resources/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: core/resources/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: core/resources/fonts/Rubik-Black.ttf
          weight: 900
    - family: Unbounded
      fonts:
        - asset: core/resources/fonts/Unbounded-SemiBold.ttf
          weight: 600
        - asset: core/resources/fonts/Unbounded-ExtraBold.ttf
          weight: 800
