name: wasdrop
description: WasDrop - merge drop game
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0"
  flutter: ">=3.27.0"

dependencies:
  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  navigation:
    path: ./navigation
  features:
    path: ./features

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flame: ^1.38.0

flutter:
  uses-material-design: true

  assets:
    - core/resources/audio/

  fonts:
    - family: Archivo
      fonts:
        - asset: core/resources/fonts/Archivo-SemiBold.ttf
          weight: 600
        - asset: core/resources/fonts/Archivo-ExtraBold.ttf
          weight: 800
        - asset: core/resources/fonts/Archivo-Black.ttf
          weight: 900
