name: core_ui
version: 0.0.1
publish_to: none
description: core UI module

environment:
  sdk: ">=3.5.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
